**The link can be found below**

https://www.bilibili.com/video/BV1ce411K7XC?p=15&spm_id_from=pageDriver&vd_source=7cca4a20f2401942703a8c8eff4d7492

In [1]:
import torch
import torch.nn as nn

The type of pooling layers:
- Max
- Min
- Avg
- Global Avg(An alternative way for flatten)

## Max-pooling

*Max-pooling is used much more than average pooling with one exception which is sometimes very deep in the neural network*

The formulas to calculate the dimensions of output feature map are:

$$W_{out}=\lfloor\frac{W_{in}+2p-d\cdot(f-1)+1}{s}\rfloor+1$$
$$H_{out}=\lfloor\frac{H_{in}+2p-d\cdot(f-1)+1}{s}\rfloor+1$$

- $p$ padding
- $f$ kernel_size
- $s$ stride
- $d$ dilation

In [8]:
m = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1)
input = torch.rand(4,4)
input = torch.unsqueeze(input, dim=0)
print(input.shape)
output = m(input)
print(output.shape)

print(input)
print(output)

torch.Size([1, 4, 4])
torch.Size([1, 2, 2])
tensor([[[0.4148, 0.4937, 0.2084, 0.9672],
         [0.1777, 0.1698, 0.9329, 0.7269],
         [0.7871, 0.9162, 0.5005, 0.4857],
         [0.2629, 0.6887, 0.4815, 0.8897]]])
tensor([[[0.4937, 0.9672],
         [0.9162, 0.8897]]])


## Average-pooling
*Average-pooling 可以去除网络中的架构特性， 如 edge，texture等*

**注意：average-pooling 没有dilation操作**

The formulas to calculate the dimensions of output feature map are:

$$W_{out}=\lfloor\frac{W_{in}+2p-f}{s}\rfloor+1$$
$$H_{out}=\lfloor\frac{H_{in}+2p-f}{s}\rfloor+1$$

- $p$ padding
- $f$ kernel_size
- $s$ stride

In [9]:
m = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1)
input = torch.ones(4,4)
input = torch.unsqueeze(input, dim=0)
print(input.shape)
output = m(input)
print(output.shape)

print(input)
print(output)

torch.Size([1, 4, 4])
torch.Size([1, 2, 2])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1.],
         [1., 1.]]])


## Global Average Pooling
- GAP将每一张feature ma做平均后，变成一个输出节点，可以直接连接SoftMax
- GAP主要是在卷积层后，一种可以取代全连接层或者整合feature map的方法
- GAP的目的是对整个网络结构上做正则化防止过拟合


Pytorch 中没有专门的GAP layer，可以使用如下方式实现：

```AdaptiveAvgPool2d((1,1))```

In [10]:
m = nn.AdaptiveAvgPool2d((1,1))
input = torch.ones(3, 5, 5)
print(input.shape)
output = m(input)
print(output.shape)
print(output)

torch.Size([3, 5, 5])
torch.Size([3, 1, 1])
tensor([[[1.]],

        [[1.]],

        [[1.]]])
