**The link can be found below**

https://www.bilibili.com/video/BV1ce411K7XC?p=10&vd_source=7cca4a20f2401942703a8c8eff4d7492

In [1]:
import torch
import torch.nn as nn

## nn.Linear
https://pytorch.org/docs/stable/generated/torch.nn.Linear.html?highlight=linear#torch.nn.Linear

$$y=xA^T+b$$

Input: 
$$(*, H_{in})$$
Output:
$$(*, H_{out})$$

In [3]:
linear_layer = nn.Linear(4, 2, bias = False)
print(linear_layer.weight)

Parameter containing:
tensor([[ 0.2428, -0.2119, -0.1144,  0.2428],
        [-0.1241, -0.0758,  0.0310, -0.2176]], requires_grad=True)


In [6]:
weights = torch.Tensor(
        [[2, 2, 2, 2],
         [2, 2, 2, 2]]
        )
linear_layer.weight = nn.Parameter(weights)
print(linear_layer.weight)
print(linear_layer.weight.shape)

Parameter containing:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]], requires_grad=True)
torch.Size([2, 4])


In [5]:
input = torch.ones((2, 4))
print(input.shape)
output = linear_layer(input)
print(output.shape)
print(output)

torch.Size([2, 4])
torch.Size([2, 2])
tensor([[8., 8.],
        [8., 8.]], grad_fn=<MmBackward0>)
