In [1]:
import torch
import numpy as np

## Initialization of a tensor
There are three basic properties of a tensor in Pytorch:
- ```dtype```
- ```device```
- ```requires_grad```

In [23]:
device = torch.device('cpu', 0)
print(device)

cpu:0


In [3]:
x = torch.empty(5, 3)
print(x)
print(type(x))

tensor([[1.1561e+19, 6.8794e+11, 2.7253e+20],
        [3.0866e+29, 1.1547e+19, 4.1988e+07],
        [3.0357e+32, 1.1547e+19, 6.4069e+02],
        [4.3066e+21, 1.1547e+19, 7.3867e+20],
        [9.2358e-01, 2.5774e-12, 4.4353e+27]])
<class 'torch.Tensor'>


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7175, 0.0697, 0.4060],
        [0.4356, 0.7068, 0.3295],
        [0.3742, 0.3745, 0.6878],
        [0.0360, 0.9598, 0.0696],
        [0.6959, 0.7825, 0.6948]])


In [5]:
x = np.random.rand(5, 3)
print(x)
y = torch.tensor(x, dtype = torch.float32, device = device)
print(y)
print(y.device)

[[0.80601783 0.73113037 0.13983885]
 [0.6657179  0.9354483  0.0402669 ]
 [0.68111934 0.98597564 0.13552464]
 [0.87199893 0.71061815 0.72712647]
 [0.08473934 0.4563115  0.79775659]]
tensor([[0.8060, 0.7311, 0.1398],
        [0.6657, 0.9354, 0.0403],
        [0.6811, 0.9860, 0.1355],
        [0.8720, 0.7106, 0.7271],
        [0.0847, 0.4563, 0.7978]])
cpu


In [6]:
z = torch.from_numpy(x)
print(z)
print(z.device)

tensor([[0.8060, 0.7311, 0.1398],
        [0.6657, 0.9354, 0.0403],
        [0.6811, 0.9860, 0.1355],
        [0.8720, 0.7106, 0.7271],
        [0.0847, 0.4563, 0.7978]], dtype=torch.float64)
cpu


### Squeeze vs unsqueeze
- ```unsqueeze()``` to return a new tensor with a dimension of size one inserted at the specified position.
- ```squeeze()``` to return a tensor with all the dimensions of input of size 1 removed.

In [7]:
x = torch.rand(3, 255, 255)
print(x.shape)
y = torch.unsqueeze(x, 0)
print(y.shape)

torch.Size([3, 255, 255])
torch.Size([1, 3, 255, 255])


In [8]:
z = torch.squeeze(x)
print(z.shape)

torch.Size([3, 255, 255])


## Common Commands

In [9]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.get_device_name)
print(torch.backends.cudnn.version)

1.13.0+cpu
None
<function get_device_name at 0x000002014AB7F708>
<function version at 0x000002014B303708>


### Casting

In [10]:
x = torch.rand(5, 5, dtype = torch.float32)
print(x.dtype)

torch.float32


In [11]:
x = x.double()
print(x.dtype)

torch.float64


In [12]:
x = x.half()
print(x.dtype)

torch.float16


In [13]:
x = x.long()
print(x.dtype)

torch.int64


A very common way to define ```device``` is use a if-else:

In [14]:
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'
    
print(device)

cpu


### torch.Tensor.clone()
```clone()``` to return a copy of a tensor. Noted that the output and input tensor don't share same stroage

In [15]:
x = torch.rand(3, 5, dtype = torch.float32)
print(id(x))
y = x.clone()
print(id(y))

z = torch.sin(x)
print(id(z))

print(x.storage().data_ptr() == y.storage().data_ptr()) # different storage


2204608429016
2204608385656
2204608333048
False


### torch.Tensor.clamp()
```clamp()``` to clamp all elements in input into the range [```min```, ```max``` ].

Noted that ```x.clamp(min=0)``` can be used to define ReLU

In [16]:
x = torch.randn(3, 5)
print(x)

tensor([[ 0.2741,  1.4270,  0.4713, -0.1086,  0.6749],
        [-0.3464, -0.7055,  0.2132, -0.3279, -0.5013],
        [-1.0820, -0.0505, -2.1460,  2.1234,  0.0678]])


In [17]:
y = x.clamp(min = 0)
print(y)
print(id(x) == id(y))

tensor([[0.2741, 1.4270, 0.4713, 0.0000, 0.6749],
        [0.0000, 0.0000, 0.2132, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 2.1234, 0.0678]])
False


In [18]:
relu = torch.nn.ReLU()
z = relu(x)
print(z)
print(id(x) == id(z))

tensor([[0.2741, 1.4270, 0.4713, 0.0000, 0.6749],
        [0.0000, 0.0000, 0.2132, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 2.1234, 0.0678]])
False


### Flatten vs view
- ```torch.flatten()``` does not need shape paremeters
- ```torch.Tensor.view()``` needs shape paremeters

These two methods output tensors sharing same storage with input tensor

In [19]:
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x)
y = torch.flatten(x)
print(y)
print(id(x) == id(y))
print(x.storage().data_ptr())
print(y.storage().data_ptr()) # share same storage but with different id?

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
False
2204564839040
2204564839040


In [20]:
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x)
y = x.view(x.numel())
print(y)
print(id(x) == id(y))
print(x.storage().data_ptr())
print(y.storage().data_ptr()) # share same storage but with different id?

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
False
2204564838592
2204564838592


### torch.Tensor.item() (Slow speed)

In [21]:
x = torch.tensor(1.0)
print(x.item())

1.0


### torch.Tensor.tolist() (Slow speed)

In [22]:
x = torch.arange(1, 11)
print(x)
y = x.tolist()
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


### torch.Tensor.detach()
- 脱离graph(requires_grad = False)
- 不在计算graident梯度(保持参数weights不变)
- 只训练分支网络时